import { Inter } from 'next/font/google'
import './globals.css'
import BoltIcon from '@/components/BoltIcon'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen text-black`}>
       <main className='p-4 max-w-2xl mx-auto'>
       <header className='flex justify-between my-8'>
        <Link href='/' className='flex items-center gap-1'>
        <BoltIcon />

          <span> VoiceLyric </span>
        </Link>
          <nav className='flex gap-6 text-black/80'>
            <Link href='/'> Ana Sayfa  </Link>
            <Link href='/pricing'> Fiyatlandırma </Link>
            <Link href='/iletisim'> İletişim </Link>

          </nav>
      </header>




        {children}
        </main>
        
        </body>

    </html>
  )
}
